export interface Product {
  id: string;
  name: string;
  price: number;
  location: string;
  category: string;
  categoryImg: string;
  subCategory: string;
  subCategoryImg: string;
  phone: string;
  description: string;
  image: string;
  storeId?: string;
}

export const productsData: Product[] = [

  {
    id: '1',
    name: 'iPhone 13 Pro Max',
    price: 2000,
    location: 'ბათუმი',
    category: 'ტექნიკა',
    categoryImg: '/public/images/category-images/ტექნიკა.jpg',
    subCategory: 'ტელეფონები',
    subCategoryImg: '/public/images/subCategoryImgs/ტელეფონები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
    storeId: '1',
  },
  {
    id: '2',
    name: 'Gaming PC',
    price: 2100,
    location: 'ბათუმი',
    category: 'ტექნიკა',
    categoryImg: '/public/images/category-images/ტექნიკა.jpg',
    subCategory: 'პერსონალური-კომპიუტერები',
    subCategoryImg: '/public/images/subCategoryImgs/პერსონალური-კომპიუტერები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
    storeId: '2',
  },
  {
    id: '3',
    name: 'fexsacmeli',
    price: 2100,
    location: 'ბათუმი',
    category: 'ტანსაცმელი',
    categoryImg: '/public/images/category-images/ტანსაცმელი.jpg',
    subCategory: 'ფეხსაცმელები',
    subCategoryImg: '/public/images/subCategoryImgs/ფეხსაცმლები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '4',
    name: 'zeda',
    price: 2100,
    location: 'ბათუმი',
    category: 'ტანსაცმელი',
    categoryImg: '/public/images/category-images/ტანსაცმელი.jpg',
    subCategory: 'ზედები',
    subCategoryImg: '/public/images/subCategoryImgs/ზედები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '5',
    name: 'qamari',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'ქამრები',
    subCategoryImg: '/public/images/subCategoryImgs/ქამრები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '6',
    name: 'samajuri',
    price: 2100,
    location: 'თბილისი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '7',
    name: 'ეიფელის კოშკი',
    price: 2100,
    location: 'ბათუმი',
    category: 'რამე ერთი',
    categoryImg: '/public/images/category-images/რამე-ერთი.png',
    subCategory: 'ეიფელის კოშკი',
    subCategoryImg: '/public/images/subCategoryImgs/ეიფელის-კოშკი-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '8',
    name: 'Dzaglebi',
    price: 2100,
    location: 'ბათუმი',
    category: 'რამე ორი',
    categoryImg: '/public/images/category-images/რამე-ორი.png',
    subCategory: 'ძაღლები',
    subCategoryImg: '/public/images/subCategoryImgs/ძაღლები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '9',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '10',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '11',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '12',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '13',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '14',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '15',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '16',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },

  {
    id: '17',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '18',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '19',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '20',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '21',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '22',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '23',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '24',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '25',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '26',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '27',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '28',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '29',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '30',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },
  {
    id: '31',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },  {
    id: '32',
    name: 'samajuri',
    price: 2100,
    location: 'ბათუმი',
    category: 'აქსესუარი',
    categoryImg: '/public/images/category-images/აქსესუარი.jpg',
    subCategory: 'სამაჯურები',
    subCategoryImg: '/public/images/subCategoryImgs/სამაჯურები-ქვეკატეგორია.jpg',
    phone: '551 555 555',
    description: 'This is item description',
    image:'/public/images/grapes.jpg',
  },


];
